Instructions/Labs/AZ400_M04_Version_Controlling_with_Git_in_Azure_Repos.md
Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Instructions/Labs/AZ400_M06_Enabling_Continuous_Integration_with_Azure_Pipelines.md
Instructions/Labs/AZ400_M06_Integrating_External_Source_Control_with_Azure_Pipelines.md
Instructions/Labs/AZ400_M07_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
Instructions/Labs/AZ400_M08_GitHub_Actions_Continuous_Integration.md
Instructions/Labs/AZ400_M09_Package_Management_with_Azure_Artifacts.md
Instructions/Labs/AZ400_M10_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M10_Creating_a_Release_Dashboard.md
Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M11_Setting_Up_and_Running_Functional_Tests.md
Instructions/Labs/AZ400_M12_Feature_Flag_Management_with_LaunchDarkly_and_Azure_DevOps.md
Instructions/Labs/AZ400_M13_Azure_Deployments_Using_Resource_Manager_Templates.md
Instructions/Labs/AZ400_M14_Ansible_with_Azure.md
Instructions/Labs/AZ400_M14_Automating_infrastructure_deployments_in_the_Cloud_with_Terraform.md
Instructions/Labs/AZ400_M14_Deploy_app_with_Puppet_on_Azure.md
Instructions/Labs/AZ400_M14_Deploying_apps_with_Chef_on_Azure.md
Instructions/Labs/AZ400_M15_Modernizing_your_Existing_ASP.NET_Apps_with_Azure.md
Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md
Instructions/Labs/AZ400_M17_Monitoring_Application_Performance_with_Application_Insights.md
Instructions/Labs/AZ400_M18_Integration_between_Azure_DevOps_and_Teams.md
Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
Instructions/Labs/AZ400_M20_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md

The title in the table needs to be just 'module' to show on the following site https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/
Modules 4 to 20.

The title in the table needs to be just 'module'

---

Instructions/Labs/AZ400_M10_Controlling_Deployments_using_Release_Gates.md

Releasegates lab fix

---

Instructions/Labs/AZ400_M14_Automating_infrastructure_deployments_in_the_Cloud_with_Terraform.md

Terraform lab fix

---

Instructions/Labs/AZ400_M20_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md

updated spacing

---

Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md

- Indention corrections
- Formatting corrections.
-

Correcting indention and formatting missing asterisks

---

Instructions/Labs/AZ400_M07_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
Instructions/Labs/AZ400_M10_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M10_Creating_a_Release_Dashboard.md
Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M11_Setting_Up_and_Running_Functional_Tests.md
Instructions/Labs/AZ400_M12_Feature_Flag_Management_with_LaunchDarkly_and_Azure_DevOps.md
Instructions/Labs/AZ400_M13_Azure_Deployments_Using_Resource_Manager_Templates.md
Instructions/Labs/AZ400_M14_Ansible_with_Azure.md
Instructions/Labs/AZ400_M15_Modernizing_your_Existing_ASP.NET_Apps_with_Azure.md
Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md
Instructions/Labs/AZ400_M17_Monitoring_Application_Performance_with_Application_Insights.md

Added the d at the end of:
"In this task, you will use Azure Cloud Shell to remove the Azure resources provisioned"

Correcting one typo at the end of labs

---

Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md

Corrected indention and some typos.

Corrected indention and some typos.

---

Instructions/Labs/AZ400_M06_Enabling_Continuous_Integration_with_Azure_Pipelines.md

Mod 6 Lab Visual CI ###Task 3 ---> #### Task 3

---

Instructions/Labs/AZ400_M01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

- Added "Azure" to "DevOps organization" to clarify.

Added "Azure" to "DevOps organization" for clarification.

---

Instructions/Labs/AZ400_M13_Azure_Deployments_Using_Resource_Manager_Templates.md
Instructions/Labs/AZ400_M15_Modernizing_your_Existing_ASP.NET_Apps_with_Azure.md

-	Module 13 - Lab 1 - Exercise 1:  
o	Task 1 – Step 2: Change to the following:
o	In a web browser, connect to: https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-simple-windows/azuredeploy.json.
o	Copy the contents of the json file from Github to the Visual Studio Code window.
o	
-	Module 15 – Lab 1 – Exercise 0:
o	**NOTE** You may receive a message telling you that your Visual Studio evaluation period has expired. You can create a new account using the login you used for your Azure account.

AZ-400 Updates

---

Instructions/Labs/AZ400_M07_Integrating_Azure_Key_Vault_with_Azure_DevOps.md

Fixes # .
- Lab deletes resources without reviewing CD results
- review pipeline and created resources
-

Lab deletes resources without reviewing CD results

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md

Added markdown formatting and clarification to some of the steps.

Updated lab environment validation

---

Instructions/Labs/AZ400_M09_Package_Management_with_Azure_Artifacts.md

Exercise 1, Task 4, Step 16:
Replaced "next to the Version ** Latest stable 1.1.0** dropdown list" with "next to the Version: Latest stable 1.1.0** dropdown list"

Updated a minor markdown issue

---

Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md

…netes_Services.md
Fixes #108  .

m16-lab16: Replace token (preview) task does not take"__" as prefix/suffix, breaking pod

---

Instructions/Labs/AZ400_M11_Setting_Up_and_Running_Functional_Tests.md

change PAT from all scopes to agent pools

---

Instructions/Labs/AZ400_M08_Implementing_GitHub_Actions_by_using_DevOps_Starter.md

**Link related Github Issue** 🢂 Fixes #138  . (Include issue number after #)
- Include a warning in the instructions (as the issue may be fixed in the future)
- Related AZ CLI issue: https://github.com/Azure/cli/issues/56
-

M08-LAB08: fixing issue #138

---

Instructions/Labs/AZ400_M10_Creating_a_Release_Dashboard.md

- [ x] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝
- The table in the `md` file is not rendering correctly due to a comment
- Removing the comment will fix the issue
- I tried other solution to keep the comment but not possible, so seems like the comment must be deleted in order for the table to display correct, see if other feasible solution
Cheers!

M10-LAB10: Fix table not rendering correctly issue by removing comment

---

Instructions/Labs/AZ400_M10_Creating_a_Release_Dashboard.md

**Link related Github Issue** 🢂 Fixes #147 & Fixes #143  . (Include issue number after #)
- Adding Azure DevOps marketplace extension for missing widgets
- Adding missing steps
- Fixing typos on file name
-
-

M10-LAB10b: missing widgets and steps for dashboard

---

Instructions/Labs/AZ400_M01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

Added the proper markdown for lab 01 - Ex 03 - Task 2 -  Step 9 to fix the missing photo in the lab
**Link related Github Issue** 🢂 Fixes #169  
- Just removed the current image tag and added the proper markdown format

M01-LAB01: Fixing missing photo

---

Instructions/Labs/AZ400_M18_Integration_between_Azure_DevOps_and_Teams.md

**Link related Github Issue** 🢂 Fixes #149 and fixes #146  . (Include issue number after #)
- Updates for the Azure Boards bot
- Delete Exercise 3 --> wiki already covered in Lab 3, and repo is missing (If the steps mentioned are followed, the repository is hosted in github, not azure devops.
- Formatting 
- Use default tailwind project, not the one uploaded from Zip
-

M18-LAB18: Multiple updates

---

Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md

Updated lab 5 instructions to include clicking on the security menu in the instructions which confuses students. Also added a missing step in self hosted agent configuration
**Link related Github Issue** 🢂 Fixes #172 
- Added a step so that students know they have to click on the security menu from the dropdown before accessing personal access token option
- Added a missing step in setting up self hosted agent

M05-Lab05: Updated Lab 5 instructions

---

Instructions/Labs/AZ400_M14_Automating_infrastructure_deployments_in_the_Cloud_with_Terraform.md

**Link related Github Issue** 🢂 Fixes #150  . (Include issue number after #)
- Modify the TF file
-
-

M14-LAB14b: webapp.tf content has changed, provider registration needs to be placed before the resource configuration bug

---

Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md

…netes_Services.md
**Link related Github Issue** 🢂 Fixes #166  . (Include issue number after #)
- fix typos
-
-

M16-LAB16: fixing typos 

---

Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md

**Link related Github Issue** 🢂 Fixes #177  . (Include issue number after #)
- remove VStest task (fails due to repo update to VS2019)
- modify to windows-2019 agent
- modified a command to paste and modify REGION first.

M11-LAB11a: fix VStest issue and update to windows-2019 agent

---

Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md

M11-Lab11a Changes to fix Windows 2017 build references

---

Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md

**Link related Github Issue** 🢂 Fixes #192  . (Include issue number after #)
-
-
-

Update Lab 03

---

Instructions/Labs/AZ400_M06_Enabling_Continuous_Integration_with_Azure_Pipelines.md

**Link related Github Issue** 🢂 Fixes #181  . (Include issue number after #)
- disable tests --> PU repo needs to be updated in order to run succesfully (as mentioned in #181 )
-
-

M06-LAB06 Tests disabled

---

Instructions/Labs/AZ400_M15_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md

The docker file is in the src/MyHealth.Web folder instead of MyHealth.Web

LAB 15 - EX 02 - Task 01 - Step 04

---

Instructions/Labs/AZ400_M07_Integrating_Azure_Key_Vault_with_Azure_DevOps.md

M07-LAB07: quick fix typo

---

Instructions/Labs/AZ400_M10_Controlling_Deployments_using_Release_Gates.md

on the DevOps protal, current version seems use the name "Resource Group name for Application Insights"

M10-LAB01: Label name fix

---

Instructions/Labs/AZ400_M06_Enabling_Continuous_Integration_with_Azure_Pipelines.md

**Link related Github Issue** 🢂 Fixes #209  . (Include issue number after #)
- delete Tests tab review
-
-

M06-LAB06:no tests

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md

**Link related Github Issue** 🢂 Fixes #207  . (Include issue number after #)
-
-
-

M00-LAB00: Update ORG policies

---

Instructions/Labs/AZ400_M08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md

…_apps.md
**Link related Github Issue** 🢂 Fixes #197  . (Include issue number after #)
- delete need to copy password
-
-

M08-LAB18 quick fix

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md

- Included notes related to two recent changes 
-
-

M00-LAB00: modify lab00 notes

---

Instructions/Labs/AZ400_M03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md

…tyles.md
**Link related Github Issue** 🢂 Fixes #225 . (Include issue number after #)
-
-
-

M03-LAB04: update with fixes

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feedback.yml
.github/pull_request_template.md

Update PR/Issue templates

---

Instructions/Labs/AZ400_M03_L04_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md

Lab04 last steps were repeated

---

Instructions/Labs/AZ400_M09_L18_Monitoring_Application_Performance_with_Application_Insights.md

M09 
EX 00
TASK 02
STEP 05
I removed the note and the commands after the note in the EX 00, TASK 02, STEP 05 because they create a lot of confusion, and they don't help the student.

LAB 18 - Azure CLI throws an error when try to create webapp

---

Instructions/Labs/AZ400_M09_L18_Monitoring_Application_Performance_with_Application_Insights.md

M09
LA 18
EX 01
TASK 03
STEP  14
Azure portal option "+ Add test" is changed in "+ Add Classic Test"

M09 - LAB 18 - Azure portal option "+ Add test" is changed

---

Instructions/Labs/AZ400_M01_L02_Version_Controlling_with_Git_in_Azure_Repos.md

remove duplicated 'of the' words
- Remove duplicated words `of the`

Proposal - M01 - LAB 02 : Removed duplicated words

---

Instructions/Labs/AZ400_M04_L10_Creating_a_Release_Dashboard.md

fixed typo

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

- removing a minor formatting typo

LAB01: Extra-Character

---

Instructions/Labs/AZ400_M05_L13_Integrating_Azure_Key_Vault_with_Azure_DevOps.md

LAB13: Instructions updates (Exercise 1, Task 2, Steps 4,5,7,10)

---

Instructions/Labs/AZ400_M05_L12_Setting_Up_and_Running_Functional_Tests.md

**Link related Github Issue** 🢂 Fixes #323
- String is formatted the same as the one you remove

Fix lab 12 formatting error

---

Instructions/Labs/AZ400_M04_L09_Controlling_Deployments_using_Release_Gates.md

- change from Parts Unlimited to EShopOnWeb as scenario
- create Build Pipeline using YAML 
- create Release Gates scenarios (approval + Azure Monitor Alerts)

updated lab to EShopOnWeb scenario + cleanup

---

Instructions/Labs/AZ400_M04_L09_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M05_L11_Configuring_Pipelines_as_Code_with_YAML.md

- use EShopOnWeb scenario instead of Parts Unlimited source code
- start from the existing eshoponweb-ci.yml for Build Stage
- add Deploy Stage to publish to Azure Web App
- integrate environment:approvals as some sort of Release/Quality Gate for YAML pipeline

Petender lab11toeshop

---

Instructions/Labs/AZ400_M03_L08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md

M03-LAB08: Rewrite Lab #332 
- Use eShopOnWeb instead of Azure DevOps Demo Generator.
- Automate infrastructure deployment using Bicep

Rewrite Lab08

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md

M00-LAB00: Remove Task 20 (Demo Generator reference) #339 
- Remove Task 20

M00-LAB00: Remove Task 20 (Demo Generator reference) 

---

Instructions/Labs/AZ400_M03_L08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md

M03-LAB08: Update Lab module name #341 
- Update Lab module name to "Create and manage containers using Docker and Kubernetes"

M03-LAB08: Update Lab module name

---

Instructions/Labs/AZ400_M05_L11_Configuring_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M07_L16_Implement_Security_and_Compliance_in_an_Azure_Pipeline.md

M05-LAB11 and M07-LAB16 Fix eShopOnWeb repo links #361
- Update links to point to the new eShopOnWeb repository.

Fix eShopOnWeb repo links

---

Instructions/Labs/AZ400_M03_L08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md

Fixing typos

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

Not everybody knows what an ellipsis is, so I've added `(...)` for clarity.
**Link related Github Issue** 🢂 Fixes #380 
- Added `(...)` for clarity.

M01-LAB01: Showing what an ellipsis is

---

Instructions/Labs/AZ400_M04_L10_Creating_a_Release_Dashboard.md

LAB10:Typo in instructions
🢂 Fixes #382 
- [x ] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
Fix minor typo in instructions for lab
-
-
-

fix: az400-m04-L10 typo in instructions

---

Instructions/Labs/AZ400_M06_L15_Azure_Deployments_Using_Resource_Manager_Templates.md

Updated the lab to use Bicep instead of ARM templates
**Link related Github Issue** 🢂 Fixes #374 . (Include issue number after #)
-
-
-

Update ARM Deployment lab

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

Hotfix for the title and lab name.

Hotfix - Updating lab name and title

---

Instructions/Labs/AZ400_M03_L05_Enabling_Continuous_Integration_with_Azure_Pipelines.md

Lab M03_Lab05 CI with Azure Pipelines Refresh
Enabling Continuous Integration with Azure Pipelines #370 
- Demo Generator to eShopOnWeb Refresh.
- Add build validation to pull requests

Lab M03_Lab05 CI with Azure Pipelines Refresh

---

Instructions/Labs/AZ400_M03_L05_Implementing_GitHub_Actions_for_CI_CD.md

AZ400_M03_L05 UI clarifications

AZ400_M03_L05 UI clarifications

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

…re_Boards.md
Fix link to broken image in Task 2, step 12
-
-
-

Fixed broken link to image in Exercise 1, task 2, step 12

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md
Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
Instructions/Labs/AZ400_M02_L02_Version_Controlling_with_Git_in_Azure_Repos.md
Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Instructions/Labs/AZ400_M03_L04_Enabling_Continuous_Integration_with_Azure_Pipelines.md
Instructions/Labs/AZ400_M03_L05_Implementing_GitHub_Actions_for_CI_CD.md
Instructions/Labs/AZ400_M03_L06_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M05_L08_Configuring_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M05_L09_Setting_Up_and_Running_Functional_Tests.md
Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
Instructions/Labs/AZ400_M05_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md
Instructions/Labs/AZ400_M06_L12_Azure_Deployments_Using_Resource_Manager_Templates.md
Instructions/Labs/AZ400_M07_L13_Implement_Security_and_Compliance_in_an_Azure_Pipeline.md
Instructions/Labs/AZ400_M07_L14_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md
Instructions/Labs/AZ400_M08_L15_Package_Management_with_Azure_Artifacts.md
Instructions/Labs/AZ400_M09_L16_Monitoring_Application_Performance_with_Application_Insights.md
Instructions/Labs/AZ400_M09_L17_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md

- Updating numbering to easily resolve issues
- Removing extra spaces
- Updating links removing language and query string

All labs: quick format and typo fixes

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md

**Replace issue name LAB01: Wrong field descriptor"
Fixes #443

Change field descriptor from PartsUnlimited to eShopOnWeb

---

Instructions/Labs/AZ400_M08_L15_Package_Management_with_Azure_Artifacts.md

AZ400_M08_L15_Package_Management_with_Azure_Artifacts
NuGet was not consistently written with capital G, changed that.
Fixes #451

Correcting Nuget to NuGet

---

Instructions/Labs/AZ400_M06_L12_Azure_Deployments_Using_Resource_Manager_Templates.md

**Link related Github Issue** 🢂 Fixes #420 
- Moved the resource group creation up

LABM612: moved the rg creation up

---

Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md

**Link related Github Issue** 🢂 Fixes #445 
- Fixed the NuGet version

M3 L3 - Fixed the NuGet version

---

Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md

No issue created for this
- reflecting UI changes, correcting typos and grammar

Changed instructions to reflect latest UI changes for Key vault creation

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md

Learners were often confused with the note on top stating to skip steps 1-3 if they had a subscription. I hope this makes it clearer.
- Removed note on top
- Added one section for "Don't have subscription yet" and one for "Have a subscription"

"Validate lab environment": clarification where to begin

---

Instructions/Labs/AZ400_M09_L16_Monitoring_Application_Performance_with_Application_Insights.md

- Updated (New) lab where we replace App Insights-based performance testing focus to Azure Load Testing, as it is the recommended way now
- Deploy App Service
- Run CI/CD Pipeline
- Deploy Azure Load Testing
- Run testing
- Integrate LoadTesting task in the CI/CD pipeline

init lab updates - Azure Load Testing

---

Instructions/Labs/AZ400_M06_L12_Azure_Deployments_Using_Resource_Manager_Templates.md

- Added steps to create a service connection
- Modified the naming convention of the project to match other labs
-

Added steps to create a service connection

---

Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md

**Link related Github Issue** 🢂 Fixes #467.
- Updating warning message in case pipeline needs permission to access resources.

LAB10: Update AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md

---

Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md

**Link related Github Issue** 🢂 Fixes #463.
- Updating step and adding a note to close the alert.

LAB07: Update AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md

---

Instructions/Labs/AZ400_M05_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md

Enable Dynamic Configuration and Feature Flags
-
-
-

Fixing a typo

---

Instructions/Labs/AZ400_M03_L04_Enabling_Continuous_Integration_with_Azure_Pipelines.md

The pull request is not related to an issue
- Fixed a markdown typo
- Added a few instructions for clarity
- there was no mention of the "Edit" button when editing a file in the git repo)
- the name of the Pull request to select was not mentioned (there are 2 available at this point in the lab)

AZ400_M03_L04_Fixed typo and added extra instructions for clarity

---

Instructions/Labs/AZ400_M05_L08_Configuring_Pipelines_as_Code_with_YAML.md

The pull request is not related to an issue
- Added an extra instruction to explicitly type in "Website" in the text field if it doesn't appear in the list _(it wasn't there for me)_

AZ400_M05_L08 Added an extra instruction for clarity

---

Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md

**Link related Github Issue** 🢂 Fixes #507 . (Include issue number after #)
- Renaming Canary to DevTest 
-
-

rename Canary to DevTest for clarity

---

Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Instructions/Labs/AZ400_M06_L12_Azure_Deployments_Using_Resource_Manager_Templates.md

IN the instructions there was the string ">>>>>>> Stashed changes" probably a typo from a previous merge activity.

LAB12-EX02-TASK02 : String typo in the instructions

---

Instructions/Demos/00-setup.md
index.md

- Adding demo list to GitHub Pages

Adding demo list for future demos

---

Instructions/Labs/AZ400_M07_L14_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md

- removing one extra space to fix bolding of text

Fixing bolding issue

---

Instructions/Demos/00-setup.md
Instructions/Labs/AZ400_M00_Validate_lab_environment.md
Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
Instructions/Labs/AZ400_M02_L02_Version_Controlling_with_Git_in_Azure_Repos.md
Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Instructions/Labs/AZ400_M03_L04_Enabling_Continuous_Integration_with_Azure_Pipelines.md
Instructions/Labs/AZ400_M03_L05_Implementing_GitHub_Actions_for_CI_CD.md
Instructions/Labs/AZ400_M03_L06_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M05_L08_Configuring_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M05_L09_Setting_Up_and_Running_Tests.md
Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
Instructions/Labs/AZ400_M05_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md
Instructions/Labs/AZ400_M06_L12_Azure_Deployments_Using_Resource_Manager_Templates.md
Instructions/Labs/AZ400_M07_L13_Implement_Security_and_Compliance_in_an_Azure_Pipeline.md
Instructions/Labs/AZ400_M07_L14_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md
Instructions/Labs/AZ400_M08_L15_Package_Management_with_Azure_Artifacts.md
Instructions/Labs/AZ400_M09_L16_Monitoring_Application_Performance_with_Application_Insights.md
Instructions/Labs/AZ400_M09_L17_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md

- Due to eShopOnWeb update to the resources, updating AZ-400 Labs to reflect the change.
- Updating md files to 1. instead of sequence numbering for maintenance sanity.
- Fix typos
- Fix #550
This pull request includes changes made to several files, mainly focusing on updating file paths, correcting URL links, and renumbering steps in instructions. The changes are primarily aimed at improving the accuracy and readability of the instructions.
Changes to file paths:
* [`Instructions/Demos/00-setup.md`](diffhunk://#diff-f9473db3c30b0fe3dd90bed7497c0c83e109457b93aaee3cc98d3f80f2048133L71-R71): The `.azure` folder has been renamed to `infra` in the repository organization description.
Updates to URL links:
* [`Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Bo …

All labs: Quick fix resource names and step numbering (styling only - NO CHANGES IN STEPS OR LABS)

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
Instructions/Labs/AZ400_M02_L02_Version_Controlling_with_Git_in_Azure_Repos.md
Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M05_L08_Configuring_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M08_L15_Package_Management_with_Azure_Artifacts.md
Instructions/Labs/AZ400_M09_L16_Monitoring_Application_Performance_with_Application_Insights.md
Instructions/Labs/AZ400_M09_L17_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md

**Link related Github Issue** 🢂 Fixes #516
- Fixes the issue #516.
- Project name updated from `EShopOnWeb` to `eShopOnWeb`.

LAB15: Update from nuget to dotnet pack

---

Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M05_L08_Configuring_Pipelines_as_Code_with_YAML.md

**Link related Github Issue** 🢂 Fixes #552 
- Added missing steps to add app settings for the app

Adding steps to fix the app not running post deployments for a few labs

---

Instructions/Labs/AZ400_M03_L06_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md

No issue solved
- When a user create a new pipeline in the ADO portal, he/she finds the button **New Pipeline** if he/she has already some pipelines while the button label is **Create Pipeline** if he/she hasn't any pipeline. I add a detailed description to help students
- In the EXERCISE 03, TASK 01, STEP 05, there was the chars "**" in code snippet. I fix it using chars "<" and ">" in the instructions and code.
-

M03-L06 : Detailed explanation of New pipeline button, fix "**" chars in code

---

Instructions/Labs/AZ400_M01_L01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
Instructions/Labs/AZ400_M03_L04_Enabling_Continuous_Integration_with_Azure_Pipelines.md
Instructions/Labs/AZ400_M03_L06_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
Instructions/Labs/AZ400_M05_L09_Setting_Up_and_Running_Tests.md
Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
Instructions/Labs/AZ400_M05_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md
Instructions/Labs/AZ400_M07_L13_Implement_Security_and_Compliance_in_an_Azure_Pipeline.md
Instructions/Labs/AZ400_M07_L14_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md

**Add branch name while importing YAML in azdo**
- Add name of the main branch explicitly while importing YAML pipeline during labs
- Fix style issues (AZ400_M01_L01)

Add branch name while importing YAML in azdo

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md
Instructions/Labs/AZ400_M01_L02_Version_Control_with_Git_in_Azure_Repos.md
Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md
Instructions/Labs/AZ400_M02_L04_Enable_Continuous_Integration_with_Azure_Pipelines.md
Instructions/Labs/AZ400_M03_L07_Configure_Pipelines_as_Code_with_YAML.md
Instructions/Labs/AZ400_M03_L08_Control_Deployments_using_Release_Gates.md
Instructions/Labs/AZ400_M03_L09_Set_Up_and_Run_Functional_Tests.md
Instructions/Labs/AZ400_M04_L10_Integrate_Azure_Key_Vault_with_Azure_DevOps.md
Instructions/Labs/AZ400_M05_L12_Deployments_using_Azure_Bicep_templates.md
Instructions/Labs/AZ400_M08_L14_Monitor_Application_Performance_with_Azure_Load_Testing.md

Multiple Labs
**Link related Github Issue** 🢂 Fixes #585 
added the following additional step to the eShopOnWeb import process to set the default branch to main.
1. Go to **Repos>Branches**.
1. Hover on the **main** branch then click the ellipsis on the right of the column.
1. Click on **Set as default branch**.

Added instructions to set the main branch as default branch in labs where missing

---

Instructions/Labs/AZ400_M03_L07_Configure_Pipelines_as_Code_with_YAML.md

**Link related Github Issue** 🢂 Fixes #583  
- Change the task: DownloadBuildArtifacts@0 to task: DownloadBuildArtifacts@1 to allow pipeline to run successfully

Update AZ400_M03_L07_Configure_Pipelines_as_Code_with_YAML.md to use task DownloadBuildArtifacts@1

---

Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md

- Add two bullet points for when removing agent at the end of the lab, which describes that you might need to regenerate the PAT if you do not have it anymore.

Proposal-M02-L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles:Add more detailed info for removing agent

---

Instructions/Labs/AZ400_M03_L08_Control_Deployments_using_Release_Gates.md

**Link related Github Issue** 🢂 Fixes #600.
- Small textual changes based on the latest changes in the Azure Portal

M03_L08 small textual changes

---

Instructions/Labs/AZ400_M02_L05_Implement_GitHub_Actions_for_CI_CD.md

**Link related Github Issue** 🢂 Fixes #606 
- [ X] Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
- [ X] Tested it
- [ X] Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝
- Fixed incorrect indentation in bulleted list
-
-

LAB05: Fixed incorrect indentation in bulleted list

---

Instructions/Labs/AZ400_M00_Validate_lab_environment.md

Updating formatting for consistency, adding missing instructions related to the Service Connection created due to a product update, and refining existing steps for better understanding.

update service connection steps

---

Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md
Instructions/Labs/AZ400_M08_L14_Monitor_Application_Performance_with_Azure_Load_Testing.md

- Overall steps improvement and updates.
- Task 4 removed and added additional steps to Task 3.

Fix #621 and improve lab steps

---

Instructions/Labs/AZ400_M03_L07_Configure_Pipelines_as_Code_with_YAML.md

**M03-Configure Pipelines as Code with YAML: Bad indentation in exercice 1 - task 2 - step 26)**
**Link related Github Issue** 🢂 Fixes #639. 
- indentation of the markdown fixed

M03-Configure Pipelines as Code with YAML: Bad indentation in exercice 1 - task 2 - step 26

---

Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md

This pull request includes a small change to the `Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md` file. The change updates the URL for installing Azure CLI on Windows to include the appropriate locale and pivot parameters.
* [`Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md`](diffhunk://#diff-64e5f17f6d961e63522c7a17ddbf818bf26425a8e38d4477576d40869c83c056L243-R243): Updated the URL for installing Azure CLI on Windows to include `en-us` locale and `msi` pivot parameters.

L03-EX01-STEP05 : Update the url for downloading Azure CLI

---

Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md

This pull request updates the instructions for configuring agent pools and understanding pipeline styles in the Azure DevOps lab. The changes include clarifying file names, updating commands and URLs, and improving consistency in terminology.
* Added a note clarifying the expected naming convention of the downloaded agent zip file, which is referenced later in the installation process. (`AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.md`, [Instructions/Labs/AZ400_M02_L03_Configure_Agent_Pools_and_Understand_Pipeline_Styles.mdR146-R147](diffhunk://#diff-64e5f17f6d961e63522c7a17ddbf818bf26425a8e38d4477576d40869c83c056R146-R147))
* Updated the PowerShell command to reflect the latest version of the agent zip file (`vsts-agent-win-x64-4.255.0.zip`) and added a note to …

LAB 03 - Some fixes proposed in the issue #648

---

Instructions/Labs/AZ400_M02_L04_Enable_Continuous_Integration_with_Azure_Pipelines.md

This pull request updates the instructions in the `Instructions/Labs/AZ400_M02_L04_Enable_Continuous_Integration_with_Azure_Pipelines.md` file to improve clarity and align with the current Azure DevOps interface. The changes primarily focus on updating UI navigation steps for better accuracy.
* Updated the step for saving the pipeline definition to instruct users to click the down-facing caret next to the **Run** button and select **Save** on the **Review your pipeline YAML** pane.
* Revised the instruction for editing the pipeline to guide users to use the **Edit pipeline** option under the ellipsis menu near the **Run new** button, instead of a generic **Edit** button reference.
**Link related Github Issue** 🢂 Fixes #649  
Mark completed with "x" between brackets, "[x]", or checking the …

LAB 04 - Fix issue #649

---

Instructions/Labs/AZ400_M02_L05_Implement_GitHub_Actions_for_CI_CD.md

This pull request updates the instructions for implementing GitHub Actions for CI/CD in the `AZ400_M02_L05_Implement_GitHub_Actions_for_CI_CD.md` file. The changes focus on improving clarity and accuracy in the instructions for setting up repositories, configuring Azure resources, and committing workflow changes.
* Corrected the description of the repository URL field to "The URL for your source repository" for improved clarity. (`[Instructions/Labs/AZ400_M02_L05_Implement_GitHub_Actions_for_CI_CD.mdL61-R61](diffhunk://#diff-68b618928716b76ab0675accba75400f05a85ede3dc62c44d995a56bbe914814L61-R61)`)
* Updated the note about configuring Azure Cloud Shell to reflect the option of selecting "No storage account required" for simplicity. …

LAB05: Fix issue #650 and a ui updates

---

Instructions/Labs/AZ400_M03_L07_Configure_Pipelines_as_Code_with_YAML.md

This pull request refines the instructions in the `AZ400_M03_L07_Configure_Pipelines_as_Code_with_YAML.md` file to improve clarity, update terminology, and address potential user issues during the lab exercises. The most important changes include clarifications for handling default branches, updates to Cloud Shell setup instructions, error handling for Azure commands, and adjustments to UI terminology to reflect the latest Azure DevOps interface.
* Added a note clarifying that the "Set as default branch" option will be grayed out if the main branch is already the default.
* Updated the Cloud Shell setup instructions to reflect the latest UI changes, such as selecting "No storage account required" instead of creating storage.
* Added guidance for resolving the "The subscription is not …

LAB07 - Fix issue #652 and other typos in the lab

---

Instructions/Labs/AZ400_M03_L09_Set_Up_and_Run_Functional_Tests.md

This pull request updates the lab instructions in `AZ400_M03_L09_Set_Up_and_Run_Functional_Tests.md` to improve clarity and usability. The changes focus on enhancing guidance for pipeline creation, editing, and saving, as well as adding integration tests. Below are the most important changes grouped by theme:
* Updated the instructions for creating a pipeline to include the **Create Pipeline** option for users who don't have any existing pipelines. (`[Instructions/Labs/AZ400_M03_L09_Set_Up_and_Run_Functional_Tests.mdL75-R75](diffhunk://#diff-248b70cd86b75d2a6207a76ca5f1d784bf0e668ad05595f00fd47d892ece9064L75-R75)`)
* Added a step to edit the pipeline by pressing the **Edit** button after creation. (`[Instructions/Labs/AZ400_M03_L09_Set_Up_and_Run_Functional_Tests.mdR98](diffhunk://#diff-24 …

LAB09 - Clear some instructions and fix Issue #654

---

Instructions/Labs/AZ400_M05_L12_Deployments_using_Azure_Bicep_templates.md

This pull request updates the instructions for deploying Azure Bicep templates, focusing on parameter defaults and pipeline permissions.
Parameter updates:
* Changed the default value of the `publicIPAllocationMethod` parameter from `Dynamic` to `Static` in the `storage.bicep` template.
* Changed the default value of the `publicIpSku` parameter from `Basic` to `Standard` in the `storage.bicep` template.
Pipeline permissions:
* Added a note reminding users to give the pipeline permission to use the previously created Service Connection.
**Link related Github Issue** 🢂 Fixes #685 

LAB12: Fixed Issue #685 on public ip address

---

Instructions/Labs/AZ400_M03_L08_Control_Deployments_using_Release_Gates.md

**M03-LAB08: Missing explaination to show Realeases section on Pipelines**
**Link related Github Issue** 🢂 Fixes #687
Added how to add Releases Section under Azure DevOps Pipeline section
-
-
-

Added explanation on how to solve missing Releases section

---

Instructions/Labs/AZ400_M08_L14_Monitor_Application_Performance_with_Azure_Load_Testing.md

This pull request updates the instructions for monitoring application performance with Azure Load Testing. The main changes focus on updating task versions, improving clarity in pipeline operation steps, and correcting line references and task details to match the latest Azure DevOps UI and process.
**Pipeline and Task Updates:**
* Updated the YAML deployment task to use `AzureRmWebAppDeployment@5` instead of version 4 for more current deployment practices.
* Changed references for adding the Azure Load Testing task in the YAML script to lines 64 and 65, ensuring instructions match the actual pipeline structure. Also clarified indentation requirements for task insertion.
**User Interface and Workflow Improvements:**
* Updated instructions to use **Run pipeline** instead of **Run** for …

LAB14 - Fix Issue #696
