- Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Fixes # .
Path to VisualStudio.Tests.ps1 is wrong, should be scripts/Tests
-
-
-
> Corrected Tests Directory Path

- Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
Removed the leading 0 in module number (it's the only lab with a leading 0 shown in the overview aka.ms/az400labs)
> Removing the leading 0 in module number

- Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md
> Kubernetes lab fix unai

- Instructions/Labs/AZ400_M09_Package_Management_with_Azure_Artifacts.md
Fixes # Select nuget.exe v5.5.1 instead of Latest
> M09 : Select nuget.exe v5.5.1

- Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md
Fixes 2.
- Template name is PartsUnlimited-YAML
- Category where the template is located is General not DevOps Labs
> Correcting template name and folder

- Instructions/Labs/AZ400_M14_Automating_infrastructure_deployments_in_the_Cloud_with_Terraform.md
- Adds step to clean up resource groups at the end of the lab
> M14 - Add steps to clean up resource groups

- Instructions/Labs/AZ400_M10_Controlling_Deployments_using_Release_Gates.md
Fixed indention on a note in line 104 because it was causing wrong formatting for the following bash snippets.
This makes PR #16 obsolete.
> Correcting indention, formatting, and some typos

- Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md
Fixes # .
- Fixed typos: like trigger main--> master (repo has master)
- Delete existing and not used pipeline, it makes it really confusing (specially in the end of the lab) :(
- Provide desired YAML pipeline example for students to compare
- Clarify YAML creation process
-
> Lab11 yaml fix

- Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Current instructions show installing from website, then again using chocolatey.
Removes manual download from website instruction in favour of using the chocolatey command.
- Current instruction suggest installing packer using https://www.packer.io/downloads, but then proceeds to suggest installing using chocolatey later on.
- PR Removes instruction to download using the website in favour of using chocolatey command
> Remove duplicate reference

- Instructions/Labs/AZ400_M01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
- Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
Fixes # .
- missing steps and clarifications 
-
-
> Wiki lab fixes

- Instructions/Labs/AZ400_M06_Enabling_Continuous_Integration_with_Azure_Pipelines.md
- Corrected some grammar
- Removed an empty note
> Correcting empty note and some grammar

- Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
Fixes #37 .
-no Devspaces file anymore in main branch of template repo, only in create-ci-cd-action branch
-
-
> no Devspaces file anymore in main branch of template repo, only in create-ci-cd-action branch

- Instructions/Labs/AZ400_M09_Package_Management_with_Azure_Artifacts.md
- Corrected some markdown formatting issues
- added <nolink> to ASP.NET to not have it presented as a URL
> Corrected some markdown formatting issues, removed link from ASP.NET

- Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md
Description of issue
Attendees were not able to select ASP.NET template when creating a pipeline (it was taking the one on the repo by default)
YAML example given had some indentation issues.
Fixes #41 .
- just rename existing pipeline on the temaplte and delete trigger
-  Fixed example YAML 
-
> YAML lab module 11: not able to select template and YAML example has issues

- Instructions/Labs/AZ400_M01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
- Make WIT experience easier, students get lost with dashboard widget option (not frequently used that way from experience)
- Clarify what an ellipsis is
- Move task 5 to optional exercise:  Not enough time to finish all lab in 60 minutes and this task is more related to reporting. Dashboards may have not been explained yet in module 1.
-
-
> Lab1 Proposal/fix

- Instructions/Labs/AZ400_M10_Controlling_Deployments_using_Release_Gates.md
- Instructions/Labs/AZ400_M10_Creating_a_Release_Dashboard.md
- Instructions/Labs/AZ400_M11_Configuring_Pipelines_as_Code_with_YAML.md
- Instructions/Labs/AZ400_M14_Automating_infrastructure_deployments_in_the_Cloud_with_Terraform.md
Fixing some markdown formatting issues
> Corrected some formatting issues

- Instructions/Labs/AZ400_M03_Sharing_Team_Knowledge_using_Azure_Project_Wikis.md
Fixes #58 .
devops org --> Azure DevOps organization
> fix --> azure devops org instead of devops org

- Instructions/Labs/AZ400_M19_Implement_Security_and_Compliance_in_an_Azure_DevOps_pipeline.md
Fixes # .
- Clarify as people usually go to Pipelines>pipeline and oipen the actual pipeline called whitesource
- 
-
> lab 19: clarify setup location for whitesource extension

- Instructions/Labs/AZ400_M10_Creating_a_Release_Dashboard.md
I added some details required to complete Task 1 correctly, otherwise by default the DevOps Starter will use GitHub and the instructions will be completely different.
It's important to make sure ADO is used for the DevOps Starter.
Fixes # Added details to select Azure DevOps for the Starter, otherwise GitHub is used by default
- Extra details to select the proper option and make sure Azure DevOps is selected on the Starter
- Missing names from the options like Review+Create
> Module 10 missing instructions

- Instructions/Labs/AZ400_M05_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
Fixes #57.
- Prepare the PowerShell commands to be copied&pasted directly without the need for modification.
> Updated Mod 5 Lab 1, providing the correct steps to install the agent

- Instructions/Labs/AZ400_M02_Version_Controlling_with_Git_in_Azure_Repos.md
Fixes # There is an extra "the" in the description of the Branches section
Eliminate the extra "the" from the affected paragraph
> Eliminate extra "the" from the Branch pane explanation

- Instructions/Labs/AZ400_M16_Deploying_multi-container_application_to_Azure_Kubernetes_Services.md
The variable "SQLdatabase" doesn't exist in the pipeline variables set.
- I Removed the variable called "SQLdatabase" in the instructions because that variable doesn't exist in the variable set of the pipeline
- The appsettings.json file in the MyHealt.Web code has the name of the SQL Database in the connection string and it isn't changed by the first task of the pipeline.
> LAB 16 - EX 01 - TASK 02 - STEP 25

- .gitignore
- Instructions/Labs/AZ400_M14_Ansible_with_Azure.md
**Replace issue name M14-LAB14a:
In the lab the students are required to use VSCode but
it's not installed, so I added a part to install it so
the students can follow the steps without getting stuck
- Adding step to install VSCode on Ubuntu followed by this [guide](https://code.visualstudio.com/docs/setup/linux) which is the must generic and worked on both Ubuntu 18 and 20
> Addin part to install VSCode on remote VM

- Instructions/Labs/AZ400_M05_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
Current version of az cli requires a scope to be included when a role is specified
**Link related GitHub Issue** 🢂 Fixes #232
this replacing the service principal bash creation script with one that looks up the subscription and sets the scope to be the entire subscription which WAS the default before the AZ CLI update.
> M05-LAB12: Service Principal creation failure

- Instructions/Labs/AZ400_M03_Integrating_External_Source_Control_with_Azure_Pipelines.md
Often students will accidently create a new organization while completing the **Integrating External Source Control with Azure Pipelines** lab. This fix adds a step to ensure that the Default Directory is selected, allowing learners to select their existing org instead of creating a new one.
-This adds a simple clarification. Often the GitHub tool will select the student's Microsoft Account directory
-
-
> [Proposal]-[M03]-[Lab 07]:[Prevent a new organization from being created]

- Instructions/Labs/AZ400_M06_Automating_infrastructure_deployments_in_the_Cloud_with_Terraform.md
**Link related Github Issue** 🢂 Fixes #236
Add specific verbiage to Ex 1, Task 3, Step 7 to instruct learners to change the Token Pattern property.
> M06-LAB15: Issue with pattern matching on replace token step

- Instructions/Labs/AZ400_M05_Configuring_Pipelines_as_Code_with_YAML.md
**Link related Github Issue** 🢂 Fixes #244  . (Include issue number after #)
- Most students ended up removing extension (not necessary) and it breaks azure cli
-
-
> LAB11: delete warning and extension removal (breaks lab)

- Instructions/Labs/AZ400_M07_Package_Management_with_Azure_Artifacts.md
- deleted note mentioning single package (upstream shows more) and note for fix on update!
-
-
> Lab17: fix notes

- Instructions/Labs/AZ400_M01_Agile_Planning_and_Portfolio_Management_with_Azure_Boards.md
In Task 2, it informs the person to create a work item with title of "Add page for most recent tutorials". However, in later steps in Task 3, it refers to a work item named "Add page for most recent tutorial" - missing the "s" at the end.
Fixes #251 
-
-
-
> LAB01: Fix Work Item name references

- Instructions/Labs/AZ400_M10_Managing_technical_debt_with_SonarQube_and_Azure_DevOps.md
**Link related Github Issue** 🢂 Fixes #248  . (Include issue number after #)
-
-
-
> Lab24: renewed for UI updates

- Instructions/Labs/AZ400_M04_L10_Creating_a_Release_Dashboard.md
In Lab 10: Creating a Release Dashboard
The last step of Exercise 1, Task 2 should reference Release-3, not Release-2.
- change Release-2 to Release-3 in Exercise 1, Task 2, step 13
-
-
> Lab10: Last step of task should reference Release-3 not Release-2

- Instructions/Labs/AZ400_M04_L09_Controlling_Deployments_using_Release_Gates.md
EX0 - TASK 03 - STEP 16 - There is a typo, the word "clikc" is wrong
Change the word "clikc" with the right one "click"
> LAB09: typo "clikc" on lab instruction

- Instructions/Labs/[new] AZ400_M05_Enable_Dynamic_Configuration_and_Feature_Flags.md
M05-New LAB: Enable Dynamic Configuration and Feature Flags #330 
- Add new "Enable Dynamic Configuration and Feature Flags" lab
> Add new AppConfiguration lab

- Instructions/Labs/AZ400_M05_L14_Enable_Dynamic_Configuration_and_Feature_Flags.md
M05_L14: Use the right pipeline file name for CD #346 
- Use the right pipeline file name
> M05_L14: Use the right pipeline file name for CD

- Instructions/Labs/AZ400_M04_L09_Controlling_Deployments_using_Release_Gates.md
Because of how markdown interprets asterisks (*), they were being removed from the file paths in the instructions. Adding a backslash (\) escapes those characters to display properly.
**Link related Github Issue** 🢂 Fixes #353 
- Use escape characters in file path with asterisks (*)
> Issue-M04-L09: Added escaping of asterisks in file path

- Instructions/Labs/AZ400_M04_L09_Controlling_Deployments_using_Release_Gates.md
> M04_L09 Corrected task numeration in Exercise 0

- Instructions/Labs/AZ400_M03_L08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
The option is `Rename/move` not `Rename/Remove`
Fixes #349 
- Fix typo
> M03-L08: Fix typo

- Instructions/Labs/AZ400_M03_L07_Implementing_GitHub_Actions_for_CI_CD.md
**Link related Github Issue** 🢂 Fixes #343  . (Include issue number after #)
-
-
-
> M03-LAB GH Action, fixes issue 343

- Instructions/Labs/AZ400_M03_L04_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
**Link related Github Issue** 🢂 Fixes #292  #315   . (Include issue number after #)
-
-
-
> M03-LAB04 fix for issues 292 and 315

- Instructions/Labs/AZ400_M03_L08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
** #365  M03-LAB08: NEED TO FIX TYPOS AND SHOTEN A METHOD**
**Link related Github Issue** 🢂 Fixes #365 
- Fixed typos at line 214 
- Removed an empty note at line 224
- At line 218, Instead of clicking recently pipeline and get inside pipeline summary, we can simply hover over to that pipeline and get option to **rename/move** option. This shorten method a little bit.
> Fixed typos , Removed an empty note, Short method

- Instructions/Labs/AZ400_M04_L09_Controlling_Deployments_using_Release_Gates.md
Changing signal name from **Failed Requests**  to **Requests** because failed requests doesn't exist.
No affect to the further process of lab
**M04-LAB09: NEED TO CHANGE SIGNAL NAME #366 **
**Link related Github Issue** 🢂 Fixes #366  
- Fixing the **signal name** when searching **Failed Requests** under  **create an alert rule** -> **conditions**
> Changing signal name

- Instructions/Labs/AZ400_M06_L15_Azure_Deployments_Using_Resource_Manager_Templates.md
**Link related Github Issue** 🢂 Fixing #397 and #396 
- Added the steps to create the resource group
- Added the name of the storage account parameter to the bicep module
> Updated Lab 15 to fix a few issues

- Instructions/Labs/AZ400_M03_L08_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
- changed  one line, as the RG is not created previosly on the instructions 
-
-
> M03 Lab Docker --> quick fix

- Instructions/Labs/AZ400_M03_L04_Enabling_Continuous_Integration_with_Azure_Pipelines.md
Changes to match the current UI and for clarity.
-
-
-
> Update AZ400_M03_L04 for UI changes

- Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md
Fixes #447 
Correcting trigger label and other UI misalignments.
> Changed texts for step 8, fixing issue

- Instructions/Labs/AZ400_M05_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md
**M05_L11_Enable_Dynamic_Configuration_and_Feature_Flags: Button name**
**Link related Github Issue** 🢂 Fixes #386 .
- Add create New Pipeline button
> M05_L11-Add create New Pipeline button

- Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
To complete the build, the agent computer needs Visual Studio Community Edition and some .NET SDKs installed.
Helps resolve #351 by clarifying what is needed for setting up an agent on one's own computer.
Documentation fix in the lab noting the need for Visual Studio and .NET SDKs
> Issue-M03-Configuring Agent Pools:Provide info about host software needed

- .github/ISSUE_TEMPLATE/bug.yml
**Link related Github Issue** 🢂 Fixes #464  . (Include issue number after #)
-
-
-
> Update bug or issue report

- Instructions/Labs/AZ400_M03_L06_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
> Fixing several issues and typos

- Instructions/Labs/AZ400_M03_L06_Deploying_Docker_containers_to_Azure_App_Service_web_apps.md
#453 
- changed docker to Docker in a full sentence (not command, not path)
- corrected label of existing YAML file (small f in the UI)
Left out a note/warning for the permitting of the first run of the pipelines, this needs to be addressed more broadly, affects several labs.
> Typos corrected (docker, file)

- Instructions/Labs/AZ400_M03_L04_Enabling_Continuous_Integration_with_Azure_Pipelines.md
**M03-LAB04: Replace .Net 6 reference with .Net only**
M03-LAB04: Replace .Net 6 reference with .Net only #472
- Replace .Net 6 reference with .Net only
> M03-LAB04: Replace .Net 6 reference with .Net only

- Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
- Updated Parts Unlimited to EShopOnWeb
- updated lab naming convention
- validated steps
> updated PU to EShopOnWeb

- Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
- Updating lab requirements (.NET 6)
> Updating .NET requirement

- Instructions/Labs/AZ400_M03_L03_Configuring_Agent_Pools_and_Understanding_Pipeline_Styles.md
**Link related Github Issue** 🢂 Fixes #489.
- Code improvement in YAML syntax for Azure Pipeline
> M03-LAB03: YAML Syntax Enhancement

- Instructions/Labs/AZ400_M03_L05_Implementing_GitHub_Actions_for_CI_CD.md
It is not related to an issue.
LAB M03_L05: the students find the development environments already created in the environment list. I added a note to explain them that if the environment is already there, they simply need to configure it.
> LAB_M03_L05: The development environment already exists in the original repo

- Instructions/Labs/AZ400_M00_Validate_lab_environment.md
The pull request is not related to an issue
The new organizations are created with the switches "Disable creation of classic build pipelines" and "Disable creation of classic release pipelines" set to on. It means that the students cannot create classic pipelines (build and release) and the options to create them (for example the Release option in the Pipeline in a project) will be not visible.
The students need to create those kind of pipeline in the labs and they need the option.
> LAB00 - Enable classic pipeline creation for the Organization

- Instructions/Labs/AZ400_M04_L07_Controlling_Deployments_using_Release_Gates.md
LAB 07 - EX 03 - TASK 01 - STEPS 10,14
The App Service Deployment template in the classic release pipeline has, at the moment, only one task. In the instructions, the student find **1 job, 2 tasks** but it is not right, because now is **1 job, 1 task**
> LAB07-EX03-Task01: the app service deployment template has 1 tasks not 2

- Instructions/Labs/AZ400_M05_L10_Integrating_Azure_Key_Vault_with_Azure_DevOps.md
This pull request is not related to an issue
- LAB 10 - EX 01 - TASK 01 - STEP 06: In the Service Connections page, if you don't have any connections previously created, the command to create a new service connection is not on top on the page, but in the center and the label is "Create service connection"
-LAB 10 - EX 01 - TASK 01 - STEP 08 : there is a typo here (probably). The word "the" must be "then" 
-
> LAB10 - Ui changes for new service connection and a typo

- Instructions/Labs/AZ400_M09_L16_Monitoring_Application_Performance_with_Application_Insights.md
Added UseMemory and Development settings to AzureRmWebAppDeployment@4 task
Lab16 - Include appsettings in deployment
Issue: #560 560
Checklist
Has related GitHub Issue 💥 [Create Issue](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#reporting-issues) 📝
Tested it
Read the PR collaboration guide 👓 [Collaboration Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#pull-requests) 📝
This PR changes the AzureRmWebAppDeployment@4 deployment step to include an appsettings property to allow for the dotnet 8 …
> Lab16 - Include appsettings in deployment

- Instructions/Labs/AZ400_M08_L14_Monitor_Application_Performance_with_Azure_Load_Testing.md
Added instructions to create a service principal manually since Azure Load Test doesn't support workload identities yet
**Link related Github Issue** 🢂 Fixes #571 
- Added steps to manually add the service connection
> Lab14 - Added instructions to create a service principal manually

- Instructions/Labs/AZ400_M04_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md
In the portal, the App settings has been moved to a new panel titled, **Environment Variables**. This makes that correction.
**Link related Github Issue** 🢂 Fixes #584
- Updates the instructions from Configuration and App Settings to Environment Variables
> Update AZ400_M04_L11 Update Configuration to Environment Variables

- Instructions/Labs/AZ400_M04_L11_Enable_Dynamic_Configuration_and_Feature_Flags.md
If following along to AZ400_M04_L12 the eshoponweb-ci pipeline will trigger eshoponweb-cd-webapp-code which creates the target resource group, even if it was deleted.
🢂 Fixes #612 . (Include issue number after #)
- Update documentation to provide a specific reminder to disable a pipeline that will rebuild deleted resource groups and resources
> M04_L11: A YAML pipeline will re-create a deleted resource group if the pipeline is left in place when done

- Instructions/Labs/AZ400_M08_L14_Monitor_Application_Performance_with_Azure_Load_Testing.md
Found a typo left over from a prior rename. This results in:
```
##[error]The Azure Load Testing resource eShopOnWebLoadTesting does not exist. Please provide an existing resource.
```
- Change the resource group reference in the Load Test task to refer to the new name of the recently renamed resource group
> Trivial Fix: A resource group reference named after a prior name was left in place

- Instructions/Labs/AZ400_M01_L01_Agile_Plan_and_Portfolio_Management_with_Azure_Boards.md
**Link related Github Issue** 🢂 Fixes #631 
- Change `sepcify` into `specify`
- Remove unnecessary escaping with backslashes in code block for asterisks
> 631-M01-LAB01: Correct typo and wrongly escaped text in Definition of Done text

- Instructions/Labs/AZ400_M02_L04_Enable_Continuous_Integration_with_Azure_Pipelines.md
This pull request includes a change to the instructions for enabling Continuous Integration in Azure Pipelines. The change updates the button name to reflect the current UI.
* [`Instructions/Labs/AZ400_M02_L04_Enable_Continuous_Integration_with_Azure_Pipelines.md`](diffhunk://#diff-864e4acfee9343a4ecf14e14333d20aa7979fc7b5d45cf4c5d0da23a3f4dcea0L171-R171): Updated the button name from "Save" to "Validate and save" to ensure accuracy with the current Azure Pipelines interface.
> LAB04 : EX02-TASK02-STEP03: The button label to save the pipeline is "Validate and save" instead "Save"

- Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md
This pull request includes a change to the `Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md` file to improve the clarity and accuracy of the instructions for creating a NuGet package.
Improvements to instructions:
* Changed the code block language identifier from `text` to `powershell` for better syntax highlighting in the command to navigate to the `eShopOnWeb.Shared` folder.
* Updated the command to create a `.nupkg` file to include a `PackageId` parameter, allowing users to specify a unique package name.
* Enhanced the explanatory note to clarify the purpose of the `PackageId` parameter and provide an example of its usage.
> LAB13-EX01-TASK02-STEP10: Add argument to dotnet pack command to create a package with unique name

- Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md
This pull request includes a small update to the instructions for creating a new project in the `AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md` file. The change clarifies that the `Class Library` template should target .NET or .NET Standard.
> LAB13-EX01-STEP03: Added detailed instructions to select the C# project that targets .NET or .NET standard

- Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md
This pull request updates the instructions for managing NuGet packages in Azure Artifacts to improve clarity and accuracy. The most important changes include modifying the package name and fixing navigation commands, as well as adding details to handle potential authorization errors.
* Updated the package name in the `dotnet nuget push` command to reflect a more specific naming convention (`eShopOnWeb-XXXXXX.Shared.1.0.0.nupkg` instead of `eShopOnWeb.Shared.1.0.0.nupkg`).
* Added a clarification about handling "401 Unauthorized" errors by installing the Azure Artifacts Credential Provider. This provides better guidance for users encountering authentication issues.
* Corrected the navigation command in the PowerShell instructions to ensure users navigate back two levels (`cd ../..`) …
> Lab13 fix for some issues

- Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md
This pull request includes a minor correction to the `Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md` file. The change ensures consistency in the placeholder value for the `PackageId` parameter in the `dotnet pack` command. 
* [`Instructions/Labs/AZ400_M07_L13_Package_Management_with_Azure_Artifacts.md`](diffhunk://#diff-3573b2705dcfb4d03dc2951426d433c481984fde784f83382fc88ec5cba51558L156-R156): Updated the placeholder `XXXXX` to `XXXXXX` in the `dotnet pack` command to match the instructions.
> LAB13: Fix typo placeholder in dotnet pack command for NuGet package creation

- Instructions/Labs/AZ400_M05_L12_Deployments_using_Azure_Bicep_templates.md
This pull request includes a minor update to the instructions for deploying Azure Bicep templates. The change clarifies the task description by specifying the `simple-windows-vm.bicep` template instead of the generic "main template."
> LAB12-EX01-TASK03: Clarify task description in lab instructions to specify the use of the simple-windows-vm template
